import { useContext, useMemo, useState, type ReactNode } from "react";
import { createStableContext } from "./stable-context";
import {
  reviewsSeed,
  type HumanReview,
  type ReviewHistoryEntry,
  type ReviewStatus,
} from "./review-data";
import { useRole } from "./role-context";

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/** "12 Sep · 12:18" — stable format used across review history and case timelines. */
export function stamp(date = new Date()) {
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${pad(date.getDate())} ${MONTHS[date.getMonth()]} · ${pad(date.getHours())}:${pad(
    date.getMinutes(),
  )}`;
}

export interface AccountReviewEvent {
  at: string;
  label: string;
  detail: string;
  reviewId: string;
}

interface ReviewsContextValue {
  allReviews: HumanReview[];
  /** Reviews the current role is authorized to see. */
  visibleReviews: HumanReview[];
  reviewsForClient: (clientId: string) => HumanReview[];
  reviewsForRule: (ruleId: string) => HumanReview[];
  reviewsForAccount: (accountId: string) => HumanReview[];
  /** Case-timeline entries generated by human review decisions. */
  accountReviewEvents: (accountId: string) => AccountReviewEvent[];
  notifications: HumanReview[];
  counts: { awaiting: number; highPriority: number; dueToday: number; onHold: number };
  canDecide: (review: HumanReview) => boolean;
  /** Modify / guide the AI recommendation — a separate supervisor permission. */
  canModify: (review: HumanReview) => boolean;
  approve: (id: string) => void;
  modify: (id: string, input: { action: string; guidance: string }) => void;
  reject: (id: string, input: { reason: string; comment: string }) => void;
  hold: (id: string, input: { until: string; reason: string }) => void;
}

const ReviewsContext = createStableContext<ReviewsContextValue | null>("reviews", null);

export function ReviewsProvider({ children }: { children: ReactNode }) {
  const [allReviews, setAllReviews] = useState<HumanReview[]>(reviewsSeed);
  const { isAdmin, visibleClientIds, userName, can } = useRole();

  const value = useMemo<ReviewsContextValue>(() => {
    const visibleReviews = isAdmin
      ? allReviews
      : allReviews.filter((r) => visibleClientIds.includes(r.clientId));

    const patch = (
      id: string,
      changes: Partial<HumanReview>,
      entries: ReviewHistoryEntry[],
    ) =>
      setAllReviews((prev) =>
        prev.map((r) =>
          r.id === id ? { ...r, ...changes, history: [...entries, ...r.history] } : r,
        ),
      );

    const setStatus = (
      id: string,
      status: ReviewStatus,
      changes: Partial<HumanReview>,
      entries: ReviewHistoryEntry[],
    ) => patch(id, { status, ...changes }, entries);

    const awaiting = visibleReviews.filter((r) => r.status === "Awaiting Review");

    return {
      allReviews,
      visibleReviews,
      reviewsForClient: (clientId) => visibleReviews.filter((r) => r.clientId === clientId),
      reviewsForRule: (ruleId) => visibleReviews.filter((r) => r.ruleId === ruleId),
      reviewsForAccount: (accountId) => visibleReviews.filter((r) => r.accountId === accountId),
      accountReviewEvents: (accountId) =>
        visibleReviews
          .filter((r) => r.accountId === accountId)
          .flatMap((r) =>
            r.history
              .slice()
              .reverse()
              .filter(
                (h) =>
                  h.event.startsWith("Human review created") ||
                  h.by !== undefined ||
                  h.event.includes("released") ||
                  h.event.includes("reassessment"),
              )
              .map((h) => ({
                at: h.at,
                label: h.event,
                detail: h.detail ?? `Review ${r.id}`,
                reviewId: r.id,
              })),
          ),
      notifications: awaiting.slice(0, 4),
      counts: {
        awaiting: awaiting.length,
        highPriority: awaiting.filter((r) => r.priority === "High").length,
        // Demo definition: waiting less than 24 hours is due today.
        dueToday: awaiting.filter((r) => r.waitingMinutes < 1440).length,
        onHold: visibleReviews.filter((r) => r.status === "On Hold").length,
      },
      canDecide: (review) => can("Approve Human Reviews", review.clientId),
      canModify: (review) => can("Modify / Guide AI Recommendation", review.clientId),
      approve: (id) => {
        const review = allReviews.find((r) => r.id === id);
        if (!review) return;
        const at = stamp();
        setStatus(
          id,
          "Approved",
          { finalAction: review.proposedAction, assignedSupervisor: userName },
          [
            {
              at,
              event: "Next collection action released",
              detail: review.proposedAction,
              by: userName,
            },
            {
              at,
              event: "Approved by supervisor",
              detail: `Governance requirement satisfied · ${review.ruleName}`,
              by: userName,
            },
          ],
        );
      },
      modify: (id, input) => {
        const review = allReviews.find((r) => r.id === id);
        if (!review) return;
        const at = stamp();
        setStatus(
          id,
          "Modified",
          { finalAction: input.action, guidance: input.guidance, assignedSupervisor: userName },
          [
            { at, event: "Adjusted action released", detail: input.action, by: userName },
            {
              at,
              event: "Supervisor guidance recorded",
              detail: input.guidance || "No additional guidance",
              by: userName,
            },
            {
              at,
              event: "Supervisor modified recommendation",
              detail: `PayFlow proposed "${review.proposedAction}" · final action "${input.action}"`,
              by: userName,
            },
          ],
        );
      },
      reject: (id, input) => {
        const at = stamp();
        setStatus(
          id,
          "Rejected",
          {
            finalAction: "Proposed action cancelled — case returned for reassessment",
            rejectionReason: input.reason,
            assignedSupervisor: userName,
          },
          [
            {
              at,
              event: "Reassessment requested",
              detail: "Customer context updated, alternative strategy to be proposed",
              by: userName,
            },
            {
              at,
              event: "Proposed action cancelled",
              detail: input.comment ? `${input.reason} — ${input.comment}` : input.reason,
              by: userName,
            },
            { at, event: "Rejected by supervisor", detail: input.reason, by: userName },
          ],
        );
      },
      hold: (id, input) => {
        const at = stamp();
        const until = input.until.trim() || "Further review";
        setStatus(
          id,
          "On Hold",
          { holdUntil: until, finalAction: "Collection activity paused", assignedSupervisor: userName },
          [
            {
              at,
              event: "Collection activity respects hold",
              detail: `Held until ${until}`,
              by: userName,
            },
            {
              at,
              event: "Placed on hold by supervisor",
              detail: input.reason || "No reason provided",
              by: userName,
            },
          ],
        );
      },
    };
  }, [allReviews, isAdmin, visibleClientIds, userName, can]);

  return <ReviewsContext.Provider value={value}>{children}</ReviewsContext.Provider>;
}

export function useReviews() {
  const ctx = useContext(ReviewsContext);
  if (!ctx) throw new Error("useReviews must be used inside ReviewsProvider");
  return ctx;
}
