/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as CommunicationsIndexRouteImport } from './routes/communications.index'
import { Route as CommunicationsCommunicationIdRouteImport } from './routes/communications.$communicationId'
import { Route as HumanReviewIndexRouteImport } from './routes/human-review.index'
import { Route as HumanReviewReviewIdRouteImport } from './routes/human-review.$reviewId'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as IntegrationsIntegrationIdRouteImport } from './routes/integrations.$integrationId'
import { Route as JourneysIndexRouteImport } from './routes/journeys.index'
import { Route as JourneysJourneyIdRouteImport } from './routes/journeys.$journeyId'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PortfoliosPortfolioIdRouteImport } from './routes/portfolios.$portfolioId'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as RulesRuleIdRouteImport } from './routes/rules.$ruleId'
import { Route as RulesNewRouteImport } from './routes/rules.new'
import { Route as StrategiesIndexRouteImport } from './routes/strategies.index'
import { Route as StrategiesStrategyIdRouteImport } from './routes/strategies.$strategyId'
import { Route as StrategiesNewRouteImport } from './routes/strategies.new'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PlatformProductsIndexRouteImport } from './routes/platform.products.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsIndexRoute = CommunicationsIndexRouteImport.update({
  id: '/communications/',
  path: '/communications/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsCommunicationIdRoute =
  CommunicationsCommunicationIdRouteImport.update({
    id: '/communications/$communicationId',
    path: '/communications/$communicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HumanReviewIndexRoute = HumanReviewIndexRouteImport.update({
  id: '/human-review/',
  path: '/human-review/',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanReviewReviewIdRoute = HumanReviewReviewIdRouteImport.update({
  id: '/human-review/$reviewId',
  path: '/human-review/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIntegrationIdRoute =
  IntegrationsIntegrationIdRouteImport.update({
    id: '/integrations/$integrationId',
    path: '/integrations/$integrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysJourneyIdRoute = JourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosPortfolioIdRoute = PortfoliosPortfolioIdRouteImport.update({
  id: '/portfolios/$portfolioId',
  path: '/portfolios/$portfolioId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRuleIdRoute = RulesRuleIdRouteImport.update({
  id: '/rules/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewRoute = RulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesStrategyIdRoute = StrategiesStrategyIdRouteImport.update({
  id: '/strategies/$strategyId',
  path: '/strategies/$strategyId',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesNewRoute = StrategiesNewRouteImport.update({
  id: '/strategies/new',
  path: '/strategies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformProductsIndexRoute = PlatformProductsIndexRouteImport.update({
  id: '/platform/products/',
  path: '/platform/products/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/communications/$communicationId': typeof CommunicationsCommunicationIdRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/strategies/$strategyId': typeof StrategiesStrategyIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/communications/': typeof CommunicationsIndexRoute
  '/human-review/': typeof HumanReviewIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/platform/products/': typeof PlatformProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/communications/$communicationId': typeof CommunicationsCommunicationIdRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/strategies/$strategyId': typeof StrategiesStrategyIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/accounts': typeof AccountsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/communications': typeof CommunicationsIndexRoute
  '/human-review': typeof HumanReviewIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/journeys': typeof JourneysIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/rules': typeof RulesIndexRoute
  '/strategies': typeof StrategiesIndexRoute
  '/users': typeof UsersIndexRoute
  '/platform/products': typeof PlatformProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/communications/$communicationId': typeof CommunicationsCommunicationIdRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/strategies/$strategyId': typeof StrategiesStrategyIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/communications/': typeof CommunicationsIndexRoute
  '/human-review/': typeof HumanReviewIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/rules/': typeof RulesIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/platform/products/': typeof PlatformProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/login'
    | '/profile'
    | '/showcase'
    | '/accounts/$accountId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/communications/$communicationId'
    | '/human-review/$reviewId'
    | '/integrations/$integrationId'
    | '/journeys/$journeyId'
    | '/pay/$token'
    | '/portfolios/$portfolioId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/strategies/$strategyId'
    | '/strategies/new'
    | '/users/$userId'
    | '/accounts/'
    | '/clients/'
    | '/communications/'
    | '/human-review/'
    | '/integrations/'
    | '/journeys/'
    | '/platform/'
    | '/rules/'
    | '/strategies/'
    | '/users/'
    | '/platform/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/login'
    | '/profile'
    | '/showcase'
    | '/accounts/$accountId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/communications/$communicationId'
    | '/human-review/$reviewId'
    | '/integrations/$integrationId'
    | '/journeys/$journeyId'
    | '/pay/$token'
    | '/portfolios/$portfolioId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/strategies/$strategyId'
    | '/strategies/new'
    | '/users/$userId'
    | '/accounts'
    | '/clients'
    | '/communications'
    | '/human-review'
    | '/integrations'
    | '/journeys'
    | '/platform'
    | '/rules'
    | '/strategies'
    | '/users'
    | '/platform/products'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/login'
    | '/profile'
    | '/showcase'
    | '/accounts/$accountId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/communications/$communicationId'
    | '/human-review/$reviewId'
    | '/integrations/$integrationId'
    | '/journeys/$journeyId'
    | '/pay/$token'
    | '/portfolios/$portfolioId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/strategies/$strategyId'
    | '/strategies/new'
    | '/users/$userId'
    | '/accounts/'
    | '/clients/'
    | '/communications/'
    | '/human-review/'
    | '/integrations/'
    | '/journeys/'
    | '/platform/'
    | '/rules/'
    | '/strategies/'
    | '/users/'
    | '/platform/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ShowcaseRoute: typeof ShowcaseRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  CommunicationsCommunicationIdRoute: typeof CommunicationsCommunicationIdRoute
  HumanReviewReviewIdRoute: typeof HumanReviewReviewIdRoute
  IntegrationsIntegrationIdRoute: typeof IntegrationsIntegrationIdRoute
  JourneysJourneyIdRoute: typeof JourneysJourneyIdRoute
  PayTokenRoute: typeof PayTokenRoute
  PortfoliosPortfolioIdRoute: typeof PortfoliosPortfolioIdRoute
  RulesRuleIdRoute: typeof RulesRuleIdRoute
  RulesNewRoute: typeof RulesNewRoute
  StrategiesStrategyIdRoute: typeof StrategiesStrategyIdRoute
  StrategiesNewRoute: typeof StrategiesNewRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  CommunicationsIndexRoute: typeof CommunicationsIndexRoute
  HumanReviewIndexRoute: typeof HumanReviewIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PlatformProductsIndexRoute: typeof PlatformProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications/': {
      id: '/communications/'
      path: '/communications'
      fullPath: '/communications/'
      preLoaderRoute: typeof CommunicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications/$communicationId': {
      id: '/communications/$communicationId'
      path: '/communications/$communicationId'
      fullPath: '/communications/$communicationId'
      preLoaderRoute: typeof CommunicationsCommunicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-review/': {
      id: '/human-review/'
      path: '/human-review'
      fullPath: '/human-review/'
      preLoaderRoute: typeof HumanReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-review/$reviewId': {
      id: '/human-review/$reviewId'
      path: '/human-review/$reviewId'
      fullPath: '/human-review/$reviewId'
      preLoaderRoute: typeof HumanReviewReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$integrationId': {
      id: '/integrations/$integrationId'
      path: '/integrations/$integrationId'
      fullPath: '/integrations/$integrationId'
      preLoaderRoute: typeof IntegrationsIntegrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$journeyId': {
      id: '/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof JourneysJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios/$portfolioId': {
      id: '/portfolios/$portfolioId'
      path: '/portfolios/$portfolioId'
      fullPath: '/portfolios/$portfolioId'
      preLoaderRoute: typeof PortfoliosPortfolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$ruleId': {
      id: '/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/rules/$ruleId'
      preLoaderRoute: typeof RulesRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new': {
      id: '/rules/new'
      path: '/rules/new'
      fullPath: '/rules/new'
      preLoaderRoute: typeof RulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies/'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/$strategyId': {
      id: '/strategies/$strategyId'
      path: '/strategies/$strategyId'
      fullPath: '/strategies/$strategyId'
      preLoaderRoute: typeof StrategiesStrategyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/new': {
      id: '/strategies/new'
      path: '/strategies/new'
      fullPath: '/strategies/new'
      preLoaderRoute: typeof StrategiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/products/': {
      id: '/platform/products/'
      path: '/platform/products'
      fullPath: '/platform/products/'
      preLoaderRoute: typeof PlatformProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ShowcaseRoute: ShowcaseRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  CommunicationsCommunicationIdRoute: CommunicationsCommunicationIdRoute,
  HumanReviewReviewIdRoute: HumanReviewReviewIdRoute,
  IntegrationsIntegrationIdRoute: IntegrationsIntegrationIdRoute,
  JourneysJourneyIdRoute: JourneysJourneyIdRoute,
  PayTokenRoute: PayTokenRoute,
  PortfoliosPortfolioIdRoute: PortfoliosPortfolioIdRoute,
  RulesRuleIdRoute: RulesRuleIdRoute,
  RulesNewRoute: RulesNewRoute,
  StrategiesStrategyIdRoute: StrategiesStrategyIdRoute,
  StrategiesNewRoute: StrategiesNewRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  CommunicationsIndexRoute: CommunicationsIndexRoute,
  HumanReviewIndexRoute: HumanReviewIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  JourneysIndexRoute: JourneysIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PlatformProductsIndexRoute: PlatformProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
