/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as HumanReviewIndexRouteImport } from './routes/human-review.index'
import { Route as HumanReviewReviewIdRouteImport } from './routes/human-review.$reviewId'
import { Route as JourneysIndexRouteImport } from './routes/journeys.index'
import { Route as RulesIndexRouteImport } from './routes/rules.index'
import { Route as RulesRuleIdRouteImport } from './routes/rules.$ruleId'
import { Route as RulesNewRouteImport } from './routes/rules.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanReviewIndexRoute = HumanReviewIndexRouteImport.update({
  id: '/human-review/',
  path: '/human-review/',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanReviewReviewIdRoute = HumanReviewReviewIdRouteImport.update({
  id: '/human-review/$reviewId',
  path: '/human-review/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIndexRoute = RulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRuleIdRoute = RulesRuleIdRouteImport.update({
  id: '/rules/$ruleId',
  path: '/rules/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewRoute = RulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/users': typeof UsersRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/human-review/': typeof HumanReviewIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/users': typeof UsersRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/human-review': typeof HumanReviewIndexRoute
  '/journeys': typeof JourneysIndexRoute
  '/rules': typeof RulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/users': typeof UsersRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/rules/$ruleId': typeof RulesRuleIdRoute
  '/rules/new': typeof RulesNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/human-review/': typeof HumanReviewIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/rules/': typeof RulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integrations'
    | '/users'
    | '/accounts/$accountId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/human-review/$reviewId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/accounts/'
    | '/clients/'
    | '/human-review/'
    | '/journeys/'
    | '/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integrations'
    | '/users'
    | '/accounts/$accountId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/human-review/$reviewId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/accounts'
    | '/clients'
    | '/human-review'
    | '/journeys'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/integrations'
    | '/users'
    | '/accounts/$accountId'
    | '/clients/$clientId'
    | '/clients/new'
    | '/human-review/$reviewId'
    | '/rules/$ruleId'
    | '/rules/new'
    | '/accounts/'
    | '/clients/'
    | '/human-review/'
    | '/journeys/'
    | '/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationsRoute: typeof IntegrationsRoute
  UsersRoute: typeof UsersRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  HumanReviewReviewIdRoute: typeof HumanReviewReviewIdRoute
  RulesRuleIdRoute: typeof RulesRuleIdRoute
  RulesNewRoute: typeof RulesNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  HumanReviewIndexRoute: typeof HumanReviewIndexRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
  RulesIndexRoute: typeof RulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-review/': {
      id: '/human-review/'
      path: '/human-review'
      fullPath: '/human-review/'
      preLoaderRoute: typeof HumanReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-review/$reviewId': {
      id: '/human-review/$reviewId'
      path: '/human-review/$reviewId'
      fullPath: '/human-review/$reviewId'
      preLoaderRoute: typeof HumanReviewReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/': {
      id: '/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof RulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$ruleId': {
      id: '/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/rules/$ruleId'
      preLoaderRoute: typeof RulesRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new': {
      id: '/rules/new'
      path: '/rules/new'
      fullPath: '/rules/new'
      preLoaderRoute: typeof RulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationsRoute: IntegrationsRoute,
  UsersRoute: UsersRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  HumanReviewReviewIdRoute: HumanReviewReviewIdRoute,
  RulesRuleIdRoute: RulesRuleIdRoute,
  RulesNewRoute: RulesNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  HumanReviewIndexRoute: HumanReviewIndexRoute,
  JourneysIndexRoute: JourneysIndexRoute,
  RulesIndexRoute: RulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
